### ISSUE TITLE
Fix error during `wasp start` after `wasp start` and failing `wasp build`

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1980]
**Version:** 0.13.2. (probably `post-0.12.0` and caused by https://github.com/wasp-lang/wasp/issues/1769#issuecomment-1952938100, doesn't happen with `0.11.8`).
**OS:** Linux

How to reproduce:
1. Run `wasp new something && cd something`.
2. Run `wasp start` and wait for it to finish.
3. Run `wasp build` and see it fail because of an inappropriate database (SQLLite).
4. Run `wasp start` again and see the error.

Here's how it looks in action:
```
$ wasp start

🐝 --- Starting compilation and setup phase. Hold tight... ------------------------


🐝 --- Compiling wasp project... --------------------------------------------------


✅ --- Successfully completed npm install. ----------------------------------------


🐝 --- Setting up database... -----------------------------------------------------


✅ --- Database successfully set up. ----------------------------------------------


🐝 --- Building SDK... ------------------------------------------------------------

wasp-bin: npx: streamingProcess: chdir: invalid argument (Bad file descriptor)
```

**Comment by sodic** [comment]
Check if it got fixed by #1769

**Comment by Rotemoyal** [comment]
I'm getting the same error while trying to setup `opensaas`.
I'm following the exact instructions in the docs (installing wasp -> wasp new -> wasp start db) and then the following wasp commands fail:
```bash
$ wasp db migrate-dev

🐝 --- Compiling wasp project... --------------------------------------------------


[  Wasp  ] Starting npm installwasp-bin: npm: streamingProcess: exec: invalid argument (Bad file descriptor)
```

```bash
$ wasp start
🐝 --- Starting compilation and setup phase. Hold tight... ------------------------


🐝 --- Compiling wasp project... --------------------------------------------------


[  Wasp  ] Starting npm installwasp-bin: npm: streamingProcess: exec: invalid argument (Bad file descriptor)
```

os: Ubuntu 24.04
wasp version: 0.13.2
node version (if it's matter): 18.19.1

any idea of how can I proceed to set it up? @sodic 
TIA!

**Comment by sodic** [comment]
Hey @Rotemoyal, thanks for letting us know!

It's not ideal, but you should be able to fix it by running `wasp clean` after any command throws this error, and then rerunning the command.

`wasp clean` won't delete anything important, it only cleans up the build artifacts, so no worries.

**Comment by Rotemoyal** [comment]
@sodic thanks for your quick response!
actually it didn't solve the issue:
```bash
$ wasp db migrate-dev

🐝 --- Compiling wasp project... --------------------------------------------------


[  Wasp  ] Starting npm installwasp-bin: npm: streamingProcess: exec: invalid argument (Bad file descriptor)

$ wasp clean

🐝 --- Deleting the .wasp/ directory... -------------------------------------------


✅ --- Deleted the .wasp/ directory. ----------------------------------------------


🐝 --- Deleting the node_modules/ directory... ------------------------------------


✅ --- Nothing to delete: The node_modules/ directory does not exist. -------------

$ wasp db migrate-dev

🐝 --- Compiling wasp project... --------------------------------------------------


[  Wasp  ] Starting npm installwasp-bin: npm: streamingProcess: exec: invalid argument (Bad file descriptor)
```

**Comment by sodic** [comment]
Hmm, strange, must be something else then. What happens when you run `npm --version`?

**Comment by Rotemoyal** [comment]
well you found it :smile: 
I'm working on a brand new PC and npm binary wasn't in `PATH`.
maybe it worth checking if  `npm` exists so the error message will be indicative?
thanks A LOT  for helping!!!

**Comment by sodic** [comment]
> maybe it worth checking if npm exists so the error message will be indicative?

Definitely!
I just made a new issue to track it: https://github.com/wasp-lang/wasp/issues/2113

Thanks for letting us know :)

**Comment by wozszym** [comment]
Had the same issue with Ubuntu 24.04 and node 18. For me it helped to upgrade node to 20 and doing a fresh wasp new.

**Comment by hellwaiver** [comment]
Getting this issue too

**Comment by hellwaiver** [comment]
Yes, it fixed the problem. But thought I'd report it anyway

**Comment by sodic** [comment]
@hellwaiver Good thing you did :)

It helps knowing how many people run into it. Thanks!

**Comment by jmcapra** [comment]
Just ran into this issue on a fresh ubuntu 24.04 and node 18, also following the opensaas template. I got past this one by installing npm, however ran into another issue at the SDK build step:

![image](https://github.com/user-attachments/assets/1ea49005-cfbf-480b-82f5-b6b19534016b)

I tried running wasp clean and running again, but same error.

**Comment by Martinsos** [comment]
> Just ran into the same issue on a fresh ubuntu 24.04 and node 18, also following the opensaas template. I got past this one by installing npm, however ran into another issue at the SDK build step:
> 
> ![image](https://private-user-images.githubusercontent.com/35404590/384630784-1ea49005-cfbf-480b-82f5-b6b19534016b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NDE4NTcsIm5iZiI6MTczMTQ0MTU1NywicGF0aCI6Ii8zNTQwNDU5MC8zODQ2MzA3ODQtMWVhNDkwMDUtY2ZiZi00ODBiLTgyZjUtYjZiMTk1MzQwMTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMDg1ZDRjNGZjYTFmNGJkMjZlNTk1MGJjODY3NjNmYTJjNTJkN2Q2OGFiYjFhYzY0Y2VjYjQ4NjdmYzBhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vOw6G-g9X4DhMz4OfCNh4HAnVP8AaTChVnqN0UXAAMs)
> 
> I tried running wasp clean and running again, but same error.

Can you try using node version 20?

**Comment by steve-quadranttech** [comment]
I am having an issue where I am trying to deploy the app to heroku but after I generate the build and try to push to heroku app is crashing, this is the log:

node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/usr/src/app/wasp'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.8.0

**Comment by NumNine9** [comment]
> Hey @Rotemoyal, thanks for letting us know!
> 
> It's not ideal, but you should be able to fix it by running `wasp clean` after any command throws this error, and then rerunning the command.
> 
> `wasp clean` won't delete anything important, it only cleans up the build artifacts, so no worries.

This solved my issue, thanks. I ran this command first `wasp clean` . Then I ran  `wasp start`

**Comment by orotibor** [comment]
Was able to replicate the issue and the problem occurs in the third step when `wasp build` returns an error message.
Caused the failure by using a dummy mail provider instead of an inappropriate database (SQLLite), however `wasp clean` solved it. 0.15.2

**Comment by sodic** [comment]
This no longer happens. Checked with 0.24.0.
