### ISSUE TITLE
[blog & docs] Add a CTA for newsletter signup

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#480]
Currently, there is no (easy) way for a blog/doc reader to sign up for our newsletter. We should add some kind of a pop-up or a permanent e.g. top bar that will invite them to do so.

**Comment by developerzeke** [comment]
@matijaSos is this resolved now?
<img width="904" alt="Image" src="https://github.com/user-attachments/assets/c52fc9c0-a0df-4870-8f45-ed8e699d1127" />

**Comment by Martinsos** [comment]
@zkmrtn8 So we do have these on the landing page, but this is about having something also on Blog and Docs! And we don't have it there yet.

**Comment by FranjoMindek** [comment]
We do have it on blog, picture above is from blog. @Martinsos

**Comment by Martinsos** [comment]
> We do have it on blog, picture above is from blog. [@Martinsos](https://github.com/Martinsos)

Aha at the bottom of the each article! I was looking at the blog homepage, it is not there, so I assumed incorrectly.
We still don't have it in the docs.

I think the idea was to have sometihng in the header, like a small link, that is visible on both blog and docs. I will let @matijaSos decide if this is done or not.
